name: Verify Identity

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: abhijit.guist@gmail.com
        run: echo "Hello, world!"
      - name: 21f1002187@ds.study.iitm.ac.in
        run: echo "Hello, world!"
